name: Jest Check

on:
  pull_request:
    branches: [develop]

jobs:
  jest:
    name: jest check
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: |
          npm install
      - name: Test PR Comment and Upload
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          coverage-command: 'npm run test -- --coverage'
          coverage-output: "./coverage/coverage-summary.json"
          comment: true
          upload: true
          upload-tag: "code-coverage-action"
          influx-host: ${{ secrets.INFLUX_HOST }}
          influx-username: admin
          influx-password: ${{ secrets.INFLUX_ALPHA}}
